### ISSUE TITLE
[Bug] Seems not to work with Postgres

### ISSUE THREAD

**Issue by Wulfheart** [LaraBug/larabug-app#88] opened 2022-06-10 20:14 UTC
According to [this output](https://flareapp.io/share/q5YEJaQ5#F65) the application does not work with Postgres. With Mysql it works fine. I recommend to remove the reference to Postgres in the Readme if I am correct.

**Comment by Cannonb4ll** [comment] 2022-06-27 11:13
Duplicate of #82

**Closed by Cannonb4ll** 2022-06-27 11:13 UTC
